### ISSUE TITLE
Use govuk-image-url helper for search button image

### ISSUE THREAD

**Issue by simonwo** [alphagov/tech-docs-gem#219]
You [recently introduced a new search button](https://github.com/alphagov/tech-docs-gem/commit/42793db1fd5477ac04e13b3134d1d4e4d53c5f24#diff-d082f5694472997fe6791f13bd87223e24d6370912ee0a0407215c5e0060436dR39) and it has a cute magnifying glass image. Thanks!

But you haven't passed the image through a call to [`govuk-image-url`](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/tools/_image-url.scss#L15) which means that downstream users who need finer-grained control over how the image URLs are formed are broken. In my case that means our ([Department for International Trade's](https://github.com/uktrade)) documentation currently doesn't display the magnifying glass and we just have an empty box. 

(To give some context to why, we override `govuk-image-url-function` to add a prefix to the root of the URL as we serve our pages from GitHub Pages.)

Would you be able to add that call please? A la:

    background-image: govuk-image-url('/images/search-button.png');

**Comment by lfdebrux** [comment]
Hi @simonwo, thanks for raising this issue, sorry it's taken us a while for us to look into it.

I'm not sure using the `govuk-image-url` function here would do what you want, because the search button image is not an image from govuk-frontend, it's actually part of this gem, and in a built site it is kept in a different location, `/images` instead of `/assets/govuk/assets/images`.

I'm curious though why serving from GitHub pages isn't working for you; is it because you have a path prefix?

**Comment by lfdebrux** [comment]
This might be addressed by https://github.com/alphagov/tech-docs-gem/pull/197

**Comment by simonwo** [comment]
Hi @lfdebrux, you are quite right that `govuk-image-url` is not the right answer – I was definitely too quick to solutionise!

The problem is indeed that we are currently serving pages from Github Pages at e.g. https://uktrade.github.io/my-repository/. As the assets are expected to be at the root they aren't found.

The workaround we used was (in `source/screen.css.scss.erb`):

```scss
$prefix: "<%= (ENV['GITHUB_REPOSITORY'] || '').partition('/')[-2..-1].join %>";

@function add-github-prefix-fonts($filename) {
  @return url($prefix + $govuk-fonts-path + $filename)
}
$govuk-font-url-function: add-github-prefix-fonts;

@function add-github-prefix-images($filename) {
  @return url($prefix + $govuk-images-path + $filename)
}
$govuk-image-url-function: add-github-prefix-images;

@import "govuk_tech_docs";
```

and then at the end of the build we do a search/replace:

```
sed -i 's:url("/images/:url("my-repository/images/:' build/stylesheets/*.css
```
